'use client';
import { useMemo, useState } from 'react';
import { PDFDownloadLink, Document, Page, Text, View, Image, StyleSheet, Font } from '@react-pdf/renderer';
import QRCode from 'qrcode';

const A4W = 595.28, A4H = 841.89;
const s = StyleSheet.create({
  page:{fontFamily:'Times-Roman',fontSize:9,padding:32,color:'#111'},
  header:{alignItems:'center',borderBottomWidth:1,borderBottomColor:'#222',paddingBottom:7,marginBottom:10},
  banner:{width:255,height:43,objectFit:'contain',marginBottom:3},
  title:{fontSize:11,fontFamily:'Times-Bold'}, sub:{fontSize:8,marginTop:2},
  h:{fontSize:11,fontFamily:'Times-Bold',marginTop:7,marginBottom:5},
  table:{borderWidth:1,borderColor:'#333'}, row:{flexDirection:'row',borderBottomWidth:1,borderBottomColor:'#333',minHeight:20},
  no:{width:'7%',padding:4,borderRightWidth:1,borderRightColor:'#333',fontFamily:'Times-Bold'}, label:{width:'35%',padding:4,borderRightWidth:1,borderRightColor:'#333',fontFamily:'Times-Bold'}, value:{width:'58%',padding:4},
  box:{borderWidth:1,borderColor:'#333',padding:8,minHeight:55}, bullet:{marginBottom:5},
  two:{flexDirection:'row',gap:12}, half:{width:'50%'}, metricRow:{flexDirection:'row',borderWidth:1,borderColor:'#333',marginBottom:-1}, metricLabel:{width:'65%',padding:5,fontFamily:'Times-Bold',borderRightWidth:1,borderRightColor:'#333'}, metricValue:{width:'35%',padding:5,textAlign:'center'},
  imgBox:{borderWidth:1,borderColor:'#333',padding:5,alignItems:'center'}, eventImg:{width:'100%',height:120,objectFit:'contain'}, photo:{width:'100%',height:155,objectFit:'contain'}, footer:{marginTop:'auto',borderTopWidth:1,borderTopColor:'#333',paddingTop:12,flexDirection:'row',justifyContent:'space-between'}, sign:{width:'30%',textAlign:'center'}, signLine:{borderTopWidth:1,borderTopColor:'#333',marginTop:22,paddingTop:5,fontFamily:'Times-Bold'},
  link:{fontSize:7}, center:{textAlign:'center'}, small:{fontSize:7}, spacer:{height:8}
});

type FormData = {
 academicYear:string; quarter:string; iicCode:string; title:string; date:string; duration:string; mode:string; venue:string; category:string; objectives:string; attendanceLink:string; ledBy:string; department:string; theme:string;
 expertName:string; expertDesignation:string; expertOrganization:string; expertAbout:string;
 hod:string; iicCoordinator:string; facultyCoordinators:string; mc:string; brief:string;
 students:string; staff:string; external:string; po:string; pso:string; highlights:string; outcome:string; feedback:string; socialPlatform:string; socialLink:string; multimediaLink:string;
 eventCoordinator:string; deptCoordinator:string; hodSign:string;
};
const initial:FormData={academicYear:'2026-27',quarter:'Q3',iicCode:'',title:'',date:'',duration:'',mode:'Offline',venue:'',category:'IIC Calendar Activity',objectives:'',attendanceLink:'',ledBy:'Institute Innovation Council',department:'',theme:'Innovation',expertName:'',expertDesignation:'',expertOrganization:'',expertAbout:'',hod:'',iicCoordinator:'',facultyCoordinators:'',mc:'',brief:'',students:'0',staff:'0',external:'0',po:'—',pso:'—',highlights:'',outcome:'',feedback:'',socialPlatform:'LinkedIn',socialLink:'',multimediaLink:'',eventCoordinator:'',deptCoordinator:'',hodSign:''};

function Header({d}:{d:FormData}){return <View style={s.header}><Image src="/nitte-header.png" style={s.banner}/><Text style={s.title}>INSTITUTION&apos;S INNOVATION COUNCIL (IIC){d.iicCode?` - ${d.iicCode}`:''}</Text><Text style={s.title}>IIC ACTIVITY REPORT</Text><Text style={s.sub}>Academic Year: {d.academicYear}     Quarter: {d.quarter}</Text></View>}
function DataRow({n,label,value}:{n:number|string,label:string,value:string}){return <View style={s.row}><Text style={s.no}>{n}</Text><Text style={s.label}>{label}</Text><Text style={s.value}>{value||' '}</Text></View>}
function PhotoBox({title,src}:{title:string,src:string}){return <View style={[s.half,s.imgBox]}><Text style={[s.center,{fontFamily:'Times-Bold',marginBottom:5}]}>{title}</Text>{src?<Image src={src} style={s.photo}/>:<View style={{height:155,justifyContent:'center'}}><Text>No image uploaded</Text></View>}</View>}
function Report({d,poster,photos,qr}:{d:FormData,poster:string,photos:string[],qr:string}){
 const rows=[[1,'Academic Year:',d.academicYear],[2,'Quarter:',d.quarter],[3,'Title of the session:',d.title],[4,'Date with Month & Year:',d.date],[5,'Duration (in hours):',d.duration],[6,'Mode:',d.mode],[7,'Venue / Platform:',d.venue],[8,'Activity Category:',d.category],[9,'Session Objectives:',d.objectives],[10,'Attendance Link:',d.attendanceLink],[11,'Activity Led by:',d.ledBy],[12,'Organizing Department:',d.department],[13,'Theme:',d.theme]] as const;
 return <Document>
 <Page size="A4" style={s.page}><Header d={d}/><Text style={s.h}>SESSION DETAILS:</Text><View style={s.table}>{rows.map(r=><DataRow key={String(r[0])} n={r[0]} label={r[1]} value={r[2]}/>)}</View><Text style={s.h}>EXPERT/SPEAKER DETAILS:</Text><View style={s.table}><DataRow n={1} label="Name:" value={d.expertName}/><DataRow n={2} label="Designation:" value={d.expertDesignation}/><DataRow n={3} label="Organization/Institution:" value={d.expertOrganization}/><DataRow n={4} label="Brief about Expert:" value={d.expertAbout}/></View></Page>
 <Page size="A4" style={s.page}><Header d={d}/><Text style={s.h}>ORGANIZING TEAM DETAILS:</Text><View style={s.box}><Text style={s.bullet}>• Head of the Department: {d.hod}</Text><Text style={s.bullet}>• IIC Coordinator: {d.iicCoordinator}</Text><Text style={s.bullet}>• Faculty Coordinators: {d.facultyCoordinators}</Text><Text style={s.bullet}>• Master of Ceremony: {d.mc}</Text></View><Text style={s.h}>BRIEF DESCRIPTION OF THE ACTIVITY (600-1000 CHARACTERS):</Text><View style={[s.box,{minHeight:420}]}><Text>{d.brief}</Text></View></Page>
 <Page size="A4" style={s.page}><Header d={d}/><View style={s.two}><View style={s.half}><Text style={s.h}>PARTICIPANT METRICS:</Text>{[['Students',d.students],['Staff',d.staff],['External',d.external]].map(x=><View style={s.metricRow} key={x[0]}><Text style={s.metricLabel}>{x[0]}</Text><Text style={s.metricValue}>{x[1]}</Text></View>)}<Text style={s.h}>MAPPING:</Text>{[['PO Mapped',d.po],['PSO Mapped',d.pso]].map(x=><View style={s.metricRow} key={x[0]}><Text style={s.metricLabel}>{x[0]}</Text><Text style={s.metricValue}>{x[1]}</Text></View>)}</View><View style={s.half}><Text style={s.h}>KEY HIGHLIGHTS:</Text><View style={[s.box,{minHeight:90}]}><Text>• {d.highlights}</Text></View></View></View><Text style={[s.h,{fontSize:8}]}>ATTENDANCE LINK: <Text style={s.link}>{d.attendanceLink}</Text></Text><Text style={s.h}>OUTCOME OF THE ACTIVITY (MAX 150 CHARS):</Text><View style={s.box}><Text>{d.outcome}</Text></View><Text style={s.h}>FEEDBACK SUMMARY:</Text><View style={[s.box,{minHeight:125}]}><Text>{d.feedback}</Text></View><View style={s.two}><View style={s.half}><Text style={s.h}>SOCIAL MEDIA COVERAGE:</Text><View style={s.box}><Text>{d.socialPlatform}</Text><Text style={s.link}>{d.socialLink}</Text></View></View><View style={s.half}><Text style={s.h}>EVENT POSTER:</Text><View style={s.imgBox}>{poster?<Image src={poster} style={s.eventImg}/>:<Text>No poster uploaded</Text>}</View></View></View></Page>
 <Page size="A4" style={s.page}><Header d={d}/><Text style={[s.h,s.center]}>SESSION VISUAL PROOFS</Text><View style={{borderTopWidth:1,borderTopColor:'#333',paddingTop:12}}/><View style={[s.two,{marginBottom:15}]}><PhotoBox title="ACTION PHOTO 1" src={photos[0]||''}/><PhotoBox title="ACTION PHOTO 2" src={photos[1]||''}/></View><View style={s.two}><PhotoBox title="ACTION PHOTO 3" src={photos[2]||''}/><PhotoBox title="ACTION PHOTO 4" src={photos[3]||''}/></View><View style={[s.box,{marginTop:14,flexDirection:'row',alignItems:'center'}]}>{qr?<Image src={qr} style={{width:75,height:75}}/>:null}<View style={{marginLeft:12,flex:1}}><Text style={s.title}>MULTIMEDIA CONTENT LINK (G-DRIVE):</Text><Text style={s.link}>{d.multimediaLink}</Text><Text style={s.small}>Scan the QR code to access photos, posters, and recorded videos of the event.</Text></View></View><View style={s.footer}><View style={s.sign}><Text>{d.eventCoordinator}</Text><Text style={s.signLine}>EVENT COORDINATOR</Text></View><View style={s.sign}><Text>{d.deptCoordinator}</Text><Text style={s.signLine}>DEPT. IIC COORDINATOR</Text></View><View style={s.sign}><Text>{d.hodSign}</Text><Text style={s.signLine}>HOD</Text></View></View></Page>
 </Document>
}
function Section({title,children}:{title:string,children:React.ReactNode}){return <section><h2>{title}</h2><div className="grid">{children}</div></section>}
function Field({label,name,value,onChange,textarea=false}:{label:string,name:keyof FormData,value:string,onChange:(n:keyof FormData,v:string)=>void,textarea?:boolean}){return <label className={textarea?'full':''}><span>{label}</span>{textarea?<textarea value={value} onChange={e=>onChange(name,e.target.value)}/>:<input value={value} onChange={e=>onChange(name,e.target.value)}/>}</label>}
export default function Home(){
 const [d,setD]=useState(initial); const [poster,setPoster]=useState(''); const [photos,setPhotos]=useState<string[]>(['','','','']); const [qr,setQr]=useState('');
 const set=(n:keyof FormData,v:string)=>setD(x=>({...x,[n]:v}));
 const file=(f:File|undefined,cb:(x:string)=>void)=>{if(!f)return;const r=new FileReader();r.onload=()=>cb(String(r.result));r.readAsDataURL(f)};
 const makeQR=async()=>setQr(d.multimediaLink?await QRCode.toDataURL(d.multimediaLink,{margin:1,width:300}):'');
 const ready=useMemo(()=>d.title.trim().length>0,[d.title]);
 return <main><header className="hero"><img src="/nitte-header.png" alt="Nitte NMAM Institute of Technology and IIC"/><div><h1>Nitte IIC Activity Report Generator</h1><p>Enter activity details, upload poster/photos, and download a four-page PDF report.</p></div></header>
 <div className="note">Template structure follows the uploaded four-page IIC Activity Report: session details, organizing team, metrics/outcomes, poster, visual proofs and signatures.</div>
 <Section title="Report & Session Details"><Field label="Academic Year" name="academicYear" value={d.academicYear} onChange={set}/><Field label="Quarter" name="quarter" value={d.quarter} onChange={set}/><Field label="IIC Code (optional)" name="iicCode" value={d.iicCode} onChange={set}/><Field label="Title of Session" name="title" value={d.title} onChange={set}/><Field label="Date" name="date" value={d.date} onChange={set}/><Field label="Duration (hours)" name="duration" value={d.duration} onChange={set}/><Field label="Mode" name="mode" value={d.mode} onChange={set}/><Field label="Venue / Platform" name="venue" value={d.venue} onChange={set}/><Field label="Activity Category" name="category" value={d.category} onChange={set}/><Field label="Activity Led by" name="ledBy" value={d.ledBy} onChange={set}/><Field label="Organizing Department" name="department" value={d.department} onChange={set}/><Field label="Theme" name="theme" value={d.theme} onChange={set}/><Field label="Session Objectives" name="objectives" value={d.objectives} onChange={set} textarea/><Field label="Attendance Link" name="attendanceLink" value={d.attendanceLink} onChange={set} textarea/></Section>
 <Section title="Expert / Speaker"><Field label="Name" name="expertName" value={d.expertName} onChange={set}/><Field label="Designation" name="expertDesignation" value={d.expertDesignation} onChange={set}/><Field label="Organization / Institution" name="expertOrganization" value={d.expertOrganization} onChange={set}/><Field label="Brief about Expert" name="expertAbout" value={d.expertAbout} onChange={set} textarea/></Section>
 <Section title="Organizing Team & Description"><Field label="Head of Department" name="hod" value={d.hod} onChange={set}/><Field label="IIC Coordinator" name="iicCoordinator" value={d.iicCoordinator} onChange={set}/><Field label="Faculty Coordinators" name="facultyCoordinators" value={d.facultyCoordinators} onChange={set}/><Field label="Master of Ceremony" name="mc" value={d.mc} onChange={set}/><Field label="Brief Description (600–1000 chars)" name="brief" value={d.brief} onChange={set} textarea/></Section>
 <Section title="Metrics, Outcome & Feedback"><Field label="Students" name="students" value={d.students} onChange={set}/><Field label="Staff" name="staff" value={d.staff} onChange={set}/><Field label="External" name="external" value={d.external} onChange={set}/><Field label="PO Mapped" name="po" value={d.po} onChange={set}/><Field label="PSO Mapped" name="pso" value={d.pso} onChange={set}/><Field label="Key Highlights" name="highlights" value={d.highlights} onChange={set} textarea/><Field label="Outcome (max 150 chars)" name="outcome" value={d.outcome} onChange={set}/><Field label="Feedback Summary" name="feedback" value={d.feedback} onChange={set} textarea/><Field label="Social Platform" name="socialPlatform" value={d.socialPlatform} onChange={set}/><Field label="Social Media Link" name="socialLink" value={d.socialLink} onChange={set} textarea/></Section>
 <Section title="Images, Multimedia & Signatures"><label><span>Event Poster</span><input type="file" accept="image/*" onChange={e=>file(e.target.files?.[0],setPoster)}/></label>{[0,1,2,3].map(i=><label key={i}><span>Action Photo {i+1}</span><input type="file" accept="image/*" onChange={e=>file(e.target.files?.[0],x=>setPhotos(p=>p.map((v,j)=>j===i?x:v)))}/></label>)}<Field label="Multimedia G-Drive Link" name="multimediaLink" value={d.multimediaLink} onChange={set}/><Field label="Event Coordinator" name="eventCoordinator" value={d.eventCoordinator} onChange={set}/><Field label="Dept. IIC Coordinator" name="deptCoordinator" value={d.deptCoordinator} onChange={set}/><Field label="HOD" name="hodSign" value={d.hodSign} onChange={set}/></Section>
 <div className="actions"><button onClick={makeQR}>Generate / Refresh QR</button>{ready?<PDFDownloadLink document={<Report d={d} poster={poster} photos={photos} qr={qr}/>} fileName={`NITTE_IIC_${d.title.replace(/[^a-z0-9]+/gi,'_')||'Activity_Report'}.pdf`} className="download">{({loading})=>loading?'Preparing PDF...':'Download PDF Report'}</PDFDownloadLink>:<button disabled>Enter session title to download</button>}</div>
 </main>;
}
